<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Wed, 18 May 2022 20:18:37 +0000
 */
$conf['title'] = 'Wiki';
$conf['lang'] = 'uk';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
