# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 18 May 2022 20:18:37 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

artem:$2y$10$250SKXhebzF6B33TJm8nvubzhJBBMAaAKOl4JVnI8lR0WqsZUduJC:Artem:mazaj561@gmail.com:admin,user
